Modules/Companies/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

/**
 * Admin routes
 */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
    Route::view('admin/prueba', 'welcome');
});

Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.'], function () {
    Route::namespace('Admin')->group(function () {
        Route::group([], function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');
            Route::get('/redirectAction/{action}/', 'DashboardController@redirectAction')->name('redirectAction');

            Route::namespace('Subsidiaries')->group(function () {
                Route::resource('subsidiaries', 'SubsidiaryController');
                Route::get('subsidiaries/{subsidiary}/recover', 'SubsidiaryController@recoverTrashedSubsidiary')->name('subsidiaries.recover');
            });
        });

        Route::namespace('EmployeeEmails')->group(function () {
            Route::resource('employee-emails', 'EmployeeEmailController');
        });

        Route::namespace('EmployeePhones')->group(function () {
            Route::resource('employee-phones', 'EmployeePhoneController');
        });

        Route::namespace('EmployeeBankData')->group(function () {
            Route::resource('employee-bank-data', 'EmployeeBankDataController');
        });

        Route::namespace('EmployeeIdentities')->group(function () {
            Route::resource('employee-identities', 'EmployeeIdentityController');
        });

        Route::namespace('EmployeeAddresses')->group(function () {
            Route::resource('employee-addresses', 'EmployeeAddressController');
        });

        Route::namespace('EmployeeEpss')->group(function () {
            Route::resource('employee-epss', 'EmployeeEpsController');
        });

        Route::namespace('EmployeeProfessions')->group(function () {
            Route::resource('employee-professions', 'EmployeeProfessionController');
        });


        Route::put('employees/{employee}/addHorary', 'EmployeeController@addHorary');
        Route::delete('employees/{employee}/deleteHorary', 'EmployeeController@deleteHorary');
        Route::put('employees/{employee}/addPenalty', 'EmployeeController@addPenalty');
        Route::delete('employees/{employee}/deletePenalty', 'EmployeeController@deletePenalty');
        Route::put('employees/{employee}/addPlatform', 'EmployeeController@addPlatform');
        Route::delete('employees/{employee}/deletePlatform', 'EmployeeController@deletePlatform');
        Route::group(['middleware' => ['role:superadmin, guard:employee']], function () {
            Route::resource('employees', 'EmployeeController');
            Route::get('employees/{employee}/profile', 'EmployeeController@getProfile')->name('employee.profile');
            Route::put('employees/{employee}/profile', 'EmployeeController@updateProfile')->name('employee.profile.update');
            Route::get('employees/{employee}/recover', 'EmployeeController@recoverTrashedEmployee')->name('employees.recover');

            Route::namespace('Roles')->group(function () {
                Route::resource('roles', 'RoleController');
                Route::get('roles/{role}/recover', 'RoleController@recoverTrashedRole')->name('roles.recover');
            });

            Route::namespace('Permissions')->group(function () {
                Route::resource('permissions', 'PermissionController');
                Route::get('permissions/{permission}/recover', 'PermissionController@recoverTrashedPermission')->name('permissions.recover');
            });


            Route::namespace('Actions')->group(function () {
                Route::resource('actions', 'ActionController');
                Route::get('actions/{actions}/recover', 'ActionController@recoverTrashedAction')->name('actions.recover');
            });
        });
        Route::resource('employee-commentaries', 'EmployeeCommentaries\EmployeeCommentaryController');
    });
});


/**
 * Frontend routes
 */

Modules/Companies/Http/Controllers/Admin/Actions/ActionController.php
<?php

namespace Modules\Companies\Http\Controllers\Admin\Actions;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Modules\Generals\Entities\Tools\ToolRepositoryInterface;
use Modules\Companies\Entities\Actions\Repositories\Interfaces\ActionRepositoryInterface;
use Modules\Companies\Entities\Actions\Repositories\ActionRepository;

class ActionController extends Controller
{
    private $actionsInterface, $toolsInterface;

    public function __construct(
        ActionRepositoryInterface $actionRepositoryInterface,
        ToolRepositoryInterface $toolRepositoryInterface
    ) {
        $this->toolsInterface   = $toolRepositoryInterface;
        $this->actionsInterface = $actionRepositoryInterface;
        $this->middleware(['permission:actions, guard:employee']);
    }

    public function index(Request $request)
    {
        $skip = request()->input('skip') ? request()->input('skip') : 0;
        $from = request()->input('from') ? request()->input('from') . " 00:00:01" : Carbon::now()->subMonths(1);
        $to   = request()->input('to') ? request()->input('to') . " 23:59:59" : Carbon::now();

        if (request()->input('q') != '' && (request()->input('from') == '' || request()->input('to') == '')) {
            $list = $this->actionsInterface->searchAction(request()->input('q'), $skip * 30);
            $paginate = $this->actionsInterface->countAction(request()->input('q'));
            $request->session()->flash('message', 'Resultado de la Busqueda');
        } elseif ((request()->input('q') != '' || request()->input('from') != '' || request()->input('to') != '')) {
            $list = $this->actionsInterface->searchAction(request()->input('q'), $skip * 30, $from, $to);
            $paginate = $this->actionsInterface->countAction(request()->input('q'), $from, $to);
            $request->session()->flash('message', 'Resultado de la Busqueda');
        } else {
            $paginate = $this->actionsInterface->countAction('');
            $list = $this->actionsInterface->listActions($skip * 30);
        }

        $paginate = ceil($paginate  / 30);
        $skipPaginate = $skip;

        $pageList = ($skipPaginate + 1) / 5;
        if (is_int($pageList) || $pageList > 1) {
            $countPage = $skipPaginate - 5;
            $maxPage = $skipPaginate + 6 > $paginate ? intval($skipPaginate + ($paginate - $skipPaginate)) : $skipPaginate + 6;
        } else {
            $countPage = 0;
            $maxPage = $skipPaginate + 5 > $paginate ? intval($skipPaginate + ($paginate - $skipPaginate)) : $skipPaginate + 5;
        }

        return view('companies::admin.actions.list', [
            'EmployeeActions' => $list,
            'optionsRoutes'   => 'admin.' . (request()->segment(2)),
            'searchInputs'    => [['label' => 'Buscar', 'type' => 'text', 'name' => 'q'], ['label' => 'Desde', 'type' => 'date', 'name' => 'from'], ['label' => 'Hasta', 'type' => 'date', 'name' => 'to']],
            'headers'         => ['ID',  'Módulo',  'Nombre',  'Ícono',  'Ruta', 'Principal',  'Opciones',],
            'skip'            => $skip,
            'pag'             => $pageList,
            'i'               => $countPage,
            'max'             => $maxPage,
            'paginate'        => $paginate
        ]);
    }

    public function create()
    {
        return view('companies::create');
    }

    public function store(Request $request)
    {
        //
    }

    public function show($id)
    {
        return view('companies::show');
    }

    public function edit($id)
    {
        return view('companies::edit');
    }


    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        $action     = $this->actionsInterface->findActionById($id);
        $actionRepo = new ActionRepository($action);
        $actionRepo->deleteAction();

        return redirect()->route('admin.actions.index')
            ->with('message', 'Eliminado Satisfactoriamente');
    }
}

Modules/Companies/Resources/views/admin/actions/create.blade.php
@extends('generals::layouts.admin.app')
@section('content')

<section class="content">
    @include('generals::layouts.errors-and-messages')
    <div class="row">
        <div class="col-12 col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.dashboard') }}"> <i class="fa fa-home"></i> Dashboard</a><span
                        class="divider"></span>
                </li>
                <li><a href="{{ route('admin.permissions.index') }}">Permisos</a><span class="divider"></span>
                <li class="breadactive">Crear Permiso</li>
            </ol>
        </div>
    </div>
    <div class="box crud-box" style="box-shadow: 0px 2px 25px rgba(0, 0, 0, .25);">
        <form action="{{ route('admin.permissions.store') }}" method="post" class="form">
            <div class="box-body">
                @csrf
                <h1>Crear Módulo</h1>
                <div class="form-group">
                    <label for="name">Nombre <span class="text-danger">*</span></label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-check"></i>
                        </div>
                        <input type="text" name="name" id="name" placeholder="Nombre" validation-pattern="name"
                            class="form-control" value="{{ old('name') }}" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="display_name">Nombre a mostrar <span class="text-danger">*</span></label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-eye"></i>
                        </div>
                        <input type="text" name="display_name" id="display_name" placeholder="Nombre a mostrar"
                            validation-pattern="name" class="form-control" value="{{ old('display_name') }}" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="icon">Ícono <span class="text-danger">*</span></label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fas fa-grip-horizontal"></i>
                        </div>
                        <input type="text" name="icon" id="icon" placeholder="Ícono" class="form-control"
                            value="{{ old('icon') }}" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="icon">Descripción</label>
                    <textarea name="description" id="description" class="form-control" validation-pattern="text"
                        rows="3">{{ old('description') }}</textarea>
                </div>
            </div>
            <div class="box-footer">
                <div class="btn-group">
                    <div class="btn-group">
                        <a href="{{ route('admin.permissions.index') }}" class="btn btn-default">Regresar</a>
                        <button type="submit" class="btn btn-primary">Crear</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
@endsection

Modules/Companies/Resources/views/admin/actions/edit.blade.php
@extends('generals::layouts.admin.app')
@section('content')

<section class="content">
    @include('generals::layouts.errors-and-messages')
    <div class="row">
        <div class="col-12 col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.dashboard') }}"> <i class="fa fa-home"></i> Dashboard</a><span
                        class="divider"></span>
                </li>
                <li><a href="{{ route('admin.permissions.index') }}">Permisos</a><span class="divider"></span>
                <li class="breadactive">{{$permission->name}}</li>
            </ol>
        </div>
    </div>
    <div class="box crud-box" style="box-shadow: 0px 2px 25px rgba(0, 0, 0, .25);">
        <form action="{{ route('admin.permissions.store') }}" method="post" class="form">
            <div class="box-body">
                @csrf
                <h1>Crear Módulo</h1>
                <div class="form-group">
                    <label for="name">Nombre <span class="text-danger">*</span></label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-check"></i>
                        </div>
                        <input type="text" name="name" id="name" placeholder="Nombre" validation-pattern="name"
                            class="form-control" value="{!! $permission->name ?: old('name')  !!}" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="display_name">Nombre a mostrar <span class="text-danger">*</span></label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-eye"></i>
                        </div>
                        <input type="text" name="display_name" id="display_name" placeholder="Nombre a mostrar"
                            validation-pattern="name" class="form-control"
                            value="{!! $permission->displya_name ?: old('display_name')  !!}" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="icon">Ícono <span class="text-danger">*</span></label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fas fa-grip-horizontal"></i>
                        </div>
                        <input type="text" name="icon" id="icon" placeholder="Ícono" class="form-control"
                            value="{!! $permission->icon ?: old('icon')  !!}" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="icon">Descripción</label>
                    <textarea name="description" id="description" validation-pattern="text" class="form-control"
                        rows="3">{!! $permission->description ?: old('description')  !!}</textarea>
                </div>
            </div>
            <div class="box-footer">
                <div class="btn-group">
                    <div class="btn-group">
                        <a href="{{ route('admin.permissions.index') }}" class="btn btn-default">Regresar</a>
                        <button type="submit" class="btn btn-primary">Crear</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
@endsection

Modules/Companies/Resources/views/admin/actions/list.blade.php
@extends('generals::layouts.admin.app')
@section('header')
<div class="header pb-2">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links">
                            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                            <li class="breadcrumb-item active" active aria-current="page">Permisos</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('content')
<section class="content">
    @include('generals::layouts.errors-and-messages')
    @if(!$EmployeeActions->isEmpty())
    <div class="card">
        <div class="card-header border-0">
            <h3 class="mb-0">Acciones</h3>
            @include('generals::layouts.search', ['route' => route('admin.actions.index')])
        </div>
        <div class="table-responsive">
            <table class="table align-items-center table-flush table-hover">
                <thead class="thead-light">
                    <tr>
                        @foreach ($headers as $header)
                        <th class="text-center" scope="col">{{ $header }} </th>
                        @endforeach
                    </tr>
                </thead>
                <tbody>
                    @foreach($EmployeeActions as $data)
                    <tr>
                        @foreach($data->toArray() as $key => $value)
                        <td class="text-center">
                            {{ $data[$key] }}
                        </td>
                        @endforeach
                        <td class="text-center">
                            @include('generals::layouts.admin..tables.table_options', [$data, 'optionsRoutes' => $optionsRoutes])
                        </td>
                    </tr>
                    <div class="modal fade" id="modal{{$data->id}}" tabindex="-1" role="dialog"
                        aria-labelledby="modelTitleId" aria-hidden="true">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Actualizar <b>{{$data->name}}</b></h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <form action="{{ route('admin.permissions.update', $data->id) }}" method="post" class="form">
                                    @method('PUT')
                                    @csrf
                                    <div class="modal-body py-0">
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <div class="form-group">
                                                    <label class="form-control-label"
                                                        for="name{{ $data->id }}">Nombre</label>
                                                    <div class="input-group input-group-merge">
                                                        <div class="input-group-prepend">
                                                            <span class="input-group-text"><i
                                                                    class="fa fa-at"></i></span>
                                                        </div>
                                                        <input type="text" name="name" id="name{{ $data->id }}"
                                                            placeholder="Nombre" validation-pattern="name"
                                                            class="form-control" required
                                                            value="{{ old('name') ?: $data->name }}">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sm-6">
                                                <div class="form-group">
                                                    <label class="form-control-label"
                                                        for="display_name{{ $data->id }}">Nombre a mostrar</label>
                                                    <div class="input-group input-group-merge">
                                                        <div class="input-group-prepend">
                                                            <span class="input-group-text"> <i
                                                                    class="fa fa-key"></i></span>
                                                        </div>
                                                        <input type="text" name="display_name" id="display_name"
                                                            placeholder="Nombre a mostrar" validation-pattern="name"
                                                            class="form-control"
                                                            value="{!! $data->displya_name ?: old('display_name')  !!}"
                                                            required>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sm-6">
                                                <div class="form-group">
                                                    <label class="form-control-label"
                                                        for="icon{{ $data->id }}">Ícono</label>
                                                    <div class="input-group input-group-merge">
                                                        <div class="input-group-prepend">
                                                            <span class="input-group-text"> <i
                                                                    class="fa fa-key"></i></span>
                                                        </div>
                                                        <input type="text" name="icon" id="icon{{ $data->id }}" placeholder="Ícono"
                                                            class="form-control"
                                                            value="{!! $data->icon ?: old('icon')  !!}" required>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sm-6">
                                                <div class="form-group">
                                                    <label class="form-control-label"
                                                        for="icon{{ $data->id }}">Descripción</label>
                                                        <textarea name="description" id="description" validation-pattern="text" class="form-control"
                                                        rows="3">{!! $data->description ?: old('description')  !!}</textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-footer text-right">
                                        <button type="submit" class="btn btn-primary btn-sm">Actualizar</button>
                                        <button type="button" class="btn btn-secondary btn-sm"
                                            data-dismiss="modal">Cerrar</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    @endforeach
                <tbody>
            </table>
        </div>
        <div class="card-footer py-4">
            @include('generals::layouts.admin.pagination.pagination', [$skip])
        </div>
    </div>
    @else
    @include('generals::layouts.admin.pagination.pagination_null', [$skip])
    @endif
</section>
@endsection