Modules/Companies/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

/**
 * Admin routes
 */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
    Route::view('admin/prueba', 'welcome');
});

Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.'], function () {
    Route::namespace('Admin')->group(function () {
        Route::group([], function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');
            Route::get('/redirectAction/{action}/', 'DashboardController@redirectAction')->name('redirectAction');

            Route::namespace('Subsidiaries')->group(function () {
                Route::resource('subsidiaries', 'SubsidiaryController');
                Route::get('subsidiaries/{subsidiary}/recover', 'SubsidiaryController@recoverTrashedSubsidiary')->name('subsidiaries.recover');
            });
        });

        Route::namespace('EmployeeEmails')->group(function () {
            Route::resource('employee-emails', 'EmployeeEmailController');
        });

        Route::namespace('EmployeePhones')->group(function () {
            Route::resource('employee-phones', 'EmployeePhoneController');
        });

        Route::namespace('EmployeeBankData')->group(function () {
            Route::resource('employee-bank-data', 'EmployeeBankDataController');
        });

        Route::namespace('EmployeeIdentities')->group(function () {
            Route::resource('employee-identities', 'EmployeeIdentityController');
        });

        Route::namespace('EmployeeAddresses')->group(function () {
            Route::resource('employee-addresses', 'EmployeeAddressController');
        });

        Route::namespace('EmployeeEpss')->group(function () {
            Route::resource('employee-epss', 'EmployeeEpsController');
        });

        Route::namespace('EmployeeProfessions')->group(function () {
            Route::resource('employee-professions', 'EmployeeProfessionController');
        });


        Route::put('employees/{employee}/addHorary', 'EmployeeController@addHorary');
        Route::delete('employees/{employee}/deleteHorary', 'EmployeeController@deleteHorary');
        Route::put('employees/{employee}/addPenalty', 'EmployeeController@addPenalty');
        Route::delete('employees/{employee}/deletePenalty', 'EmployeeController@deletePenalty');
        Route::put('employees/{employee}/addPlatform', 'EmployeeController@addPlatform');
        Route::delete('employees/{employee}/deletePlatform', 'EmployeeController@deletePlatform');
        Route::group(['middleware' => ['role:superadmin, guard:employee']], function () {
            Route::resource('employees', 'EmployeeController');
            Route::get('employees/{employee}/profile', 'EmployeeController@getProfile')->name('employee.profile');
            Route::put('employees/{employee}/profile', 'EmployeeController@updateProfile')->name('employee.profile.update');
            Route::get('employees/{employee}/recover', 'EmployeeController@recoverTrashedEmployee')->name('employees.recover');

            Route::namespace('Roles')->group(function () {
                Route::resource('roles', 'RoleController');
                Route::get('roles/{role}/recover', 'RoleController@recoverTrashedRole')->name('roles.recover');
            });

            Route::namespace('Permissions')->group(function () {
                Route::resource('permissions', 'PermissionController');
                Route::get('permissions/{permission}/recover', 'PermissionController@recoverTrashedPermission')->name('permissions.recover');
            });


            Route::namespace('Actions')->group(function () {
                Route::resource('actions', 'ActionController');
                Route::get('actions/{actions}/recover', 'ActionController@recoverTrashedAction')->name('actions.recover');
            });
        });
        Route::resource('employee-commentaries', 'EmployeeCommentaries\EmployeeCommentaryController');
    });
});


/**
 * Frontend routes
 */

Modules/Companies/Http/Controllers/Admin/Subsidiaries/SubsidiaryController.php
<?php

namespace Modules\Companies\Http\Controllers\Admin\Subsidiaries;

use Modules\Companies\Entities\Subsidiaries\Repositories\SubsidiaryRepository;
use Modules\Companies\Entities\Subsidiaries\Repositories\Interfaces\SubsidiaryRepositoryInterface;
use Modules\Companies\Entities\Subsidiaries\Requests\CreateSubsidiaryRequest;
use Modules\Companies\Entities\Subsidiaries\Requests\UpdateSubsidiaryRequest;
use Modules\Generals\Entities\Cities\Repositories\Interfaces\CityRepositoryInterface;
use App\Http\Controllers\Controller;
use Modules\Generals\Entities\Tools\ToolRepositoryInterface;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Modules\Companies\Entities\Roles\Repositories\Interfaces\RoleRepositoryInterface;

class SubsidiaryController extends Controller
{
    private $subsidiaryInterface, $cityInterface, $toolsInterface;
    private $roleInterface;

    public function __construct(
        SubsidiaryRepositoryInterface $subsidiaryRepositoryInterface,
        CityRepositoryInterface $cityRepositoryInterface,
        ToolRepositoryInterface $toolRepositoryInterface,
        RoleRepositoryInterface $roleRepositoryInterface
    ) {
        $this->toolsInterface      = $toolRepositoryInterface;
        $this->subsidiaryInterface = $subsidiaryRepositoryInterface;
        $this->cityInterface       = $cityRepositoryInterface;
        $this->roleInterface       = $roleRepositoryInterface;
        $this->middleware(['permission:subsidiaries, guard:employee']);
    }


    public function index(Request $request)
    {
        $skip    = request()->input('skip') ? request()->input('skip') : 0;
        $from    = request()->input('from') ? request()->input('from') . " 00:00:01" : Carbon::now()->subMonths(1);
        $to      = request()->input('to') ? request()->input('to') . " 23:59:59" : Carbon::now();
        $role = $this->roleInterface->findRoleById('4');
        $employees = [];
        foreach ($role->user->toArray() as $key => $value) {
            $employees[] = ['id' => $value['id'], 'label' => $value['name'] . ' ' . $value['last_name']];
        }

        if (request()->input('q') != '' && (request()->input('from') == '' || request()->input('to') == '')) {
            $list = $this->subsidiaryInterface->searchSubsidiary(request()->input('q'), $skip * 30);
            $paginate = $this->subsidiaryInterface->countSubsidiaries(request()->input('q'));
            $request->session()->flash('message', 'Resultado de la Busqueda');
        } elseif ((request()->input('q') != '' || request()->input('from') != '' || request()->input('to') != '')) {
            $list = $this->subsidiaryInterface->searchSubsidiary(request()->input('q'), $skip * 30, $from, $to);
            $paginate = $this->subsidiaryInterface->countSubsidiaries(request()->input('q'), $from, $to);
            $request->session()->flash('message', 'Resultado de la Busqueda');
        } else {
            $paginate = $this->subsidiaryInterface->countSubsidiaries('');
            $list = $this->subsidiaryInterface->listSubsidiaries($skip * 30);
        }

        $paginate = ceil($paginate  / 30);

        $skipPaginate = $skip;

        $pageList = ($skipPaginate + 1) / 5;
        if (is_int($pageList) || $pageList > 1) {
            $countPage = $skipPaginate - 5;
            $maxPage = $skipPaginate + 6 > $paginate ? intval($skipPaginate + ($paginate - $skipPaginate)) : $skipPaginate + 6;
        } else {
            $countPage = 0;
            $maxPage = $skipPaginate + 5 > $paginate ? intval($skipPaginate + ($paginate - $skipPaginate)) : $skipPaginate + 5;
        }

        return view('companies::admin.subsidiaries.list', [
            'subsidiaries'  =>  $list,
            'skip'          => $skip,
            'cities'        => $this->cityInterface->listCities(),
            'optionsRoutes' => 'admin.' . (request()->segment(2)),
            'headers'       => ['ID', 'Sucursal', 'Dirección', 'Teléfono', 'Ciudad', 'Opciones'],
            'searchInputs'    => [['label' => 'Buscar', 'type' => 'text', 'name' => 'q'], ['label' => 'Desde', 'type' => 'date', 'name' => 'from'], ['label' => 'Hasta', 'type' => 'date', 'name' => 'to']],
            'skip'          => $skip,
            'pag'           => $pageList,
            'i'             => $countPage,
            'employees'     => $employees,
            'max'           => $maxPage,
            'paginate'      => $paginate
        ]);
    }

    public function create()
    {
        $role = $this->roleInterface->findRoleById('4');
        $employees = [];
        foreach ($role->user->toArray() as $key => $value) {
            $employees[] = ['id' => $value['id'], 'label' => $value['name'] . ' ' . $value['last_name']];
        }
        return view('companies::admin.subsidiaries.create', [
            'cities' => $this->cityInterface->getAllCityNames(),
            'employees' => $employees
        ]);
    }

    public function store(CreateSubsidiaryRequest $request)
    {
        $this->subsidiaryInterface->createSubsidiary($request->except('_token', '_method'));

        return redirect()->route('admin.subsidiaries.index')
            ->with('message', 'Sucursal Creada Exitosamente!');
    }

    public function show($id)
    {
        $subsidiary = $this->subsidiaryInterface->findSubsidiaryById($id);
        $role = $this->roleInterface->findRoleById('2');
        $employees = $role->user()->where('subsidiary_id', $id)->get();
        return view('companies::admin.subsidiaries.show', [
            'subsidiary'   => $subsidiary,
            'subsidiaries' => $subsidiary->children,
            'employees'    => $employees,
        ]);
    }

    public function edit($id)
    {
        $subsidiary = $this->subsidiaryInterface->findSubsidiaryById($id);

        return view('companies::admin.subsidiaries.edit', [
            'subsidiary' => $subsidiary,
            'cities'     => $this->cityInterface->listCities(),
            'cityId'     => $subsidiary->city_id,
        ]);
    }

    public function update(UpdateSubsidiaryRequest $request, $id)
    {
        $update = new SubsidiaryRepository($this->subsidiaryInterface->findSubsidiaryById($id));
        $update->updateSubsidiary($request->except('_token', '_method'));
        $request->session()->flash('message', 'Actualizacion Exitosa');

        return redirect()->route('admin.subsidiaries.index');
    }


    public function destroy(int $id)
    {
        $subsidiary = new SubsidiaryRepository($this->subsidiaryInterface->findSubsidiaryById($id));
        $subsidiary->deleteSubsidiary();

        request()->session()->flash('message', 'Eliminado Satisfactoriamente');
        return redirect()->route('admin.subsidiaries.index');
    }

    public function recoverTrashedSubsidiary(int $id)
    {
        $subsidiaryRepo = new SubsidiaryRepository($this->subsidiaryInterface->findTrashedSubsidiaryById($id));
        $subsidiaryRepo->recoverTrashedSubsidiary();

        return redirect()->route('admin.subsidiaries.index')
            ->with('message', 'Recuperación Exitosa!');
    }
}

Modules/Companies/Resources/views/admin/subsidiaries/create.blade.php
@extends('generals::layouts.admin.app')
@section('content')

<section class="content">
    @include('generals::layouts.errors-and-messages')
    <div class="row">
        <div class="col-12 col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.dashboard') }}"> <i class="fa fa-home"></i> Dashboard</a><span
                        class="divider"></span>
                </li>
                <li><a href="{{ route('admin.subsidiaries.index') }}">Sucursales</a><span class="divider"></span>
                <li class="breadactive">Crear Sucursal</li>
            </ol>
        </div>
    </div>
    <div class="card">
        <form action="{{ route('admin.subsidiaries.store') }}" method="post" class="form" enctype="multipart/form-data">
            <div class="card-body">
                @csrf
                <div class="col pl-0 mb-3">
                    <h2>Crear Sucursal</h2>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="form-control-label" for="name">Nombre</label>
                            <div class="input-group input-group-merge">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                                </div>
                                <input type="text" name="name" id="name" validation-pattern="name" placeholder="Nombre"
                                    class="form-control" value="{{ old('name') }}" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="form-control-label" for="last_name">Dirección</label>
                            <div class="input-group input-group-merge">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                                </div>
                                <input type="text" name="address" id="address" placeholder="Dirección"
                                    validation-pattern="text" class="form-control" value="{{ old('address') }}"
                                    required>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="form-control-label" for="birthday">Teléfono</label>
                            <div class="input-group input-group-merge">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-phone"></i></span>
                                </div>
                                <input type="text" name="phone" id="phone" placeholder="Teléfono"
                                    validation-pattern="telephone" class="form-control" value="{{ old('phone') }}"
                                    required>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div id="cities" class="form-group">
                            <label class="form-control-label" for="city_id">Ciudad</label>
                            <div class="input-group">
                                <select name="city_id" id="city_id" class="form-control" enabled>
                                    @foreach($cities as $city)
                                    <option value="{{ $city->id }}">{{ $city->city }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="form-control-label" for="opening_hours">Horario Atenciòn</label>
                            <div class="input-group input-group-merge">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-clock-o"></i></span>
                                </div>
                                <input type="text" name="opening_hours" id="address" placeholder="Horario"
                                    validation-pattern="text" class="form-control" value="{{ old('opening_hours') }}"
                                    required>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div id="employees" class="form-group">
                            <label class="form-control-label" for="leader_id">Lider</label>
                            <div class="input-group">
                                <select name="leader_id" id="leader_id" class="form-control" enabled>
                                    @foreach($employees as $employee)
                                        <option value="{{ $employee['id'] }}">{{ $employee['label'] }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer text-right">
                <button type="submit" class="btn btn-primary btn-sm">Crear</button>
                <a href="{{ route('admin.subsidiaries.index') }}" class="btn btn-default btn-sm">Regresar</a>
            </div>
        </form>
    </div>


</section>

@endsection

Modules/Companies/Resources/views/admin/subsidiaries/list.blade.php
@extends('generals::layouts.admin.app')
@section('header')
<div class="header pb-2">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links">
                            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                            <li class="breadcrumb-item active" active aria-current="page">Sucursales</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('content')

<section class="content">
    @include('generals::layouts.errors-and-messages')
    @if(!$subsidiaries->isEmpty())
    <div class="card">
        <div class="card-header border-0">
            <h3 class="mb-0">Sucursales</h3>
            @include('generals::layouts.search', ['route' => route('admin.subsidiaries.index')])
        </div>
        @include('generals::layouts.admin.tables.tables_city_options', [$headers, 'datas' => $subsidiaries, $employees])
        <div class="card-footer py-2">
            @include('generals::layouts.admin.pagination.pagination', [$skip])
        </div>
    </div>
    @else
    @include('generals::layouts.admin.pagination.pagination_null', [$skip])
    @endif
</section>
@endsection

Modules/Companies/Resources/views/admin/subsidiaries/show.blade.php
@extends('generals::layouts.admin.app')
@section('header')
<div class="header pb-2">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links">
                            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.subsidiaries.index') }}">Sucursales</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">{{$subsidiary->name}}</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('content')

<section class="content">
    @include('generals::layouts.errors-and-messages')
    <div class="card">
        <div class="card-body">
            <ul class="nav nav-tabs border-0" id="infoTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#info" role="tab"
                        aria-controls="home" aria-selected="true">Información</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="managersTab" data-toggle="tab" href="#managers" role="tab"
                        aria-controls="profile" aria-selected="false">Managers - Salas</a>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="info" role="tabpanel" aria-labelledby="home-tab">
                    <div class="card">
                        <div class="card-body">
                            <div class="row align-items-center mb-3">
                                <div class="col-12">
                                    <h2>{{ $subsidiary->name }} {{ $subsidiary->city->name }}</h2>
                                    <div class="table-responsive">
                                        <table class="table align-items-center table-flush table-hover">
                                                <thead class="thead-light">
                                                <tr>
                                                    <th class="text-center" scope="col">Dirección</th>
                                                    <th class="text-center" scope="col">Telefono</th>
                                                    <th class="text-center" scope="col">Horario</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td class="text-center">{{ $subsidiary->address }}</td>
                                                    <td class="text-center">{{ $subsidiary->phone }}</td>
                                                    <td class="text-center">{{ $subsidiary->opening_hours }}</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="managers" role="tabpanel" aria-labelledby="home-tab">
                    <div class="card">
                        <div class="card-body">
                            <div class="row align-items-center mb-3">
                                <div class="col-12 col-sm-6">
                                    <h2>{{ $subsidiary->name }} {{ $subsidiary->city->name }} - Managers</h2>
                                    <div class="table-responsive">
                                        <table class="table align-items-center table-flush table-hover">
                                                <thead class="thead-light">
                                                <tr>
                                                    <th class="text-center" scope="col">Nombre</th>
                                                    <th class="text-center" scope="col">Apellido</th>
                                                    <th class="text-center" scope="col">Acciones</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach ($employees as $employee)
                                                    <tr>
                                                        <td class="text-center">{{ $employee->name }}</td>
                                                        <td class="text-center">{{ $employee->last_name }}</td>
                                                        <td class="text-center">
                                                            <a href="{{ route('admin.employees.show', $employee->id) }}" class=" table-action table-action" data-toggle="tooltip" data-original-title="Ver Empleado">
                                                                <i class="fas fa-search"></i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <h2>Salas</h2>
                                    <div class="table-responsive">
                                        <table class="table align-items-center table-flush table-hover">
                                                <thead class="thead-light">
                                                <tr>
                                                    <th class="text-center" scope="col">Nombre</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach ($subsidiary->rooms as $rooms)
                                                    <tr>
                                                        <td class="text-center">{{ $rooms->name }}</td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer">
        <div class="btn-group">
            <a href="{{ route('admin.subsidiaries.index') }}" class="btn btn-default btn-sm">Regresar</a>
        </div>
    </div>

</section>

@endsection