Modules/Customers/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

/**
 * Admin routes
 */
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.'], function () {

    Route::namespace('Admin')->group(function () {
        Route::namespace('Customers')->group(function () {
            Route::resource('customers', 'CustomerController');
            Route::resource('customer-statuses', 'CustomerStatusController');
            Route::get('customers/{customer}/recover', 'CustomerController@recoverTrashedCustomer')->name('customers.recover');
            Route::get('/api/customers', 'CustomerController@list');
            Route::get('/api/customers/{id}', 'CustomerController@getCustomer');
            Route::get('/api/listEconomicActivity', 'CustomerController@getlistEconomicActivity');
            Route::get('/api/listCities', 'CustomerController@getListCities');
            Route::get('/api/listRelationships', 'CustomerController@getRelationships');
            Route::get('/api/listCivilStatuses', 'CustomerController@getCivilStatuses');
            Route::get('/api/listGenres', 'CustomerController@getGenres');
            Route::get('/api/listScholarities', 'CustomerController@getScholarities');
            Route::get('/api/listProfessions', 'CustomerController@getProfessions');
            Route::get('/api/listVehicles', 'CustomerController@getVehicles');
            Route::get('/api/listIdentityTypes', 'CustomerController@getIdentityTypes');
            Route::get('/api/listHousings', 'CustomerController@getHousings');
            Route::get('/api/listStratums', 'CustomerController@getStratums');
            Route::get('/api/listEps', 'CustomerController@getEps');
        });
        Route::namespace('CustomerAddresses')->group(function () {
            Route::resource('customer-addresses', 'CustomerAddressController');
        });

        Route::namespace('CustomerIdentities')->group(function () {
            Route::resource('customer-identities', 'CustomerIdentityController');
        });

        Route::namespace('CustomerPhones')->group(function () {
            Route::resource('customer-phones', 'CustomerPhoneController');
        });

        Route::namespace('CustomerEpss')->group(function () {
            Route::resource('customer-epss', 'CustomerEpsController');
        });

        Route::namespace('CustomerReferences')->group(function () {
            Route::resource('customer-references', 'CustomerReferenceController');
        });

        Route::namespace('CustomerEconomicActivities')->group(function () {
            Route::resource('customer-economic-activities', 'CustomerEconomicActivityController');
        });

        Route::namespace('CustomerProfessions')->group(function () {
            Route::resource('customer-professions', 'CustomerProfessionController');
        });

        Route::namespace('CustomerVehicles')->group(function () {
            Route::resource('customer-vehicles', 'CustomerVehicleController');
        });

        Route::namespace('CustomerEmails')->group(function () {
            Route::resource('customer-emails', 'CustomerEmailController');
        });

        Route::namespace('CustomerCommentaries')->group(function () {
            Route::resource('customer-commentaries', 'CustomerCommentaryController');
        });

        Route::namespace('NewsletterSubscriptions')->group(function () {
            Route::resource('newsletter-subscription', 'NewsletterSubscriptionController');
        });
    });
});


/**
 * Frontend routes
 */
Route::namespace('Front')->group(function () {
    Route::namespace('NewsletterSubscriptions')->group(function () {
        Route::resource('newsletter-subscription', 'NewsletterSubscriptionFrontController');
    });
});

Modules/Customers/Resources/views/Admin/customer-statuses/create.blade.php
@extends('generals::layouts.admin.app')
@section('content')

<section class="content">
    @include('generals::layouts.errors-and-messages')
    <div class="row">
        <div class="col-12 col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.dashboard') }}"> <i class="fa fa-home"></i> Dashboard</a><span
                        class="divider"></span>
                </li>
                <li><a href="{{ route('admin.customer-statuses.index') }}">Estados Clientes</a><span
                        class="divider"></span>
                <li class="breadactive">Crear Estado Cliente</li>
            </ol>
        </div>
    </div>
    <div class="box crud-box" style="box-shadow: 0px 2px 25px rgba(0, 0, 0, .25);">
        <form action="{{ route('admin.customer-statuses.store') }}" method="post">
            <div class="box-body">
                <h2>Crear Estado Clientes</h2>
                @csrf
                <div class="form-group">
                    <label for="name">Nombre <span class="text-danger">*</span></label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-check"></i>
                        </div>
                        <input class="form-control" type="text" name="status" id="name" value="{{ old('status') }}"
                            placeholder="Nombre" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="color">Color <span class="text-danger">*</span></label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-paint-brush"></i>
                        </div>
                        <input class="form-control jscolor my-colorpicker1 colorpicker-element" type="text" name="color"
                            id="color" value="{{ old('color') }}" required>
                    </div>
                </div>
            </div>

            <div class="box-footer btn-group">
                <a href="{{ route('admin.customer-statuses.index') }}" class="btn btn-default">Regresar</a>
                <button type="submit" class="btn btn-primary">Crear</button>
            </div>
        </form>
    </div>

</section>
@include('layouts.admin.jscolor')
@endsection

Modules/Customers/Resources/views/Admin/customer-statuses/edit.blade.php
@extends('generals::layouts.admin.app')
@section('content')

<section class="content">
    @include('generals::layouts.errors-and-messages')
    <div class="row">
        <div class="col-12 col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.dashboard') }}"> <i class="fa fa-home"></i> Dashboard</a><span
                        class="divider"></span>
                </li>
                <li><a href="{{ route('admin.customer-statuses.index') }}">Estados Clientes</a><span
                        class="divider"></span>
                <li class="breadactive">Editar {{ $customerStatus->name}}</li>
            </ol>
        </div>
    </div>
    <div class="box crud-box" style="box-shadow: 0px 2px 25px rgba(0, 0, 0, .25);">
        <form action="{{ route('admin.customer-statuses.update', $customerStatus->id) }}" method="post">
            <div class="box-body">
                <h1>Editar Estado Clientes</h1>
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Nombre <span class="text-danger">*</span></label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-check"></i>
                        </div>
                        <input class="form-control" type="text" name="status" id="status"
                            value="{{ $customerStatus->status ?: old('status') }}" placeholder="Nombre" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="color">Color <span class="text-danger">*</span></label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-paint-brush"></i>
                        </div>
                        <input class="form-control jscolor {hash:true}" type="text" name="color" id="color"
                            value="{{ $customerStatus->color ?: old('color') }}" required>
                    </div>
                </div>
            </div>

            <div class="box-footer btn-group">
                <a href="{{ route('admin.customer-statuses.index') }}" class="btn btn-default">Regresar</a>
                <button type="submit" class="btn btn-primary">Actualizar</button>
            </div>
        </form>
    </div>

</section>
@include('layouts.admin.jscolor')
@endsection

Modules/Customers/Resources/views/Admin/customer-statuses/list.blade.php
@extends('generals::layouts.admin.app')
@section('content')

<section class="content">
    @include('generals::layouts.errors-and-messages')
    <div class="row">
        <div class="col-12 col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.dashboard') }}"> <i class="fa fa-home"></i> Dashboard</a><span
                        class="divider"></span>
                </li>
                <li><a href="{{ route('admin.customer-statuses.index') }}">Estados Clientes</a><span
                        class="divider"></span>

            </ol>
        </div>
    </div>
    @if($customerStatuses)
    <div class="box" style="box-shadow: 0px 2px 25px rgba(0, 0, 0, .25);">
        <div class="box-body">
            <h1>{{$customerStatuses->count()}} Estados Cientes</h1>
            <div class="row">
                <div class="col-md-5">
                    @include('generals::layouts.search', ['route' => route('admin.customer-statuses.index')])
                </div>
                <div class="col-md-5 float-right">
                    @include('layouts.admin.trashed-list', ['route' => route('admin.customer-statuses.index')])
                </div>
            </div>
            @include('layouts.admin.tables.tables_customer_status', [$headers, 'datas' => $customerStatuses])
        </div>

    </div>

    @endif

</section>

@endsection